# This macro is where you specifiy a CAD model, set material properties, 
# and adjust palcement of CAD model (light guide) and photon sensor (PMT)


# ----- Set world size. Must be large enough to contain CAD model. -----
/papas/worldVolume 0.25 0.25 0.25 m
/papas/envelope 89.75 113. 165. mm

# ----- Set PMT size -----
# Default PMT window is circular
/papas/model/PMTDiameter 50 mm
/papas/model/nSegmentsX 1
/papas/model/nSegmentsZ 1



#----- Set the light guide to be used and position it -----
# The desired CAD model must be an ASCII STL, and should be deopsited in the "models folder".
# If no model is selected, the program will default to a
# simplified version of the 2018 testbeam light guide.
# The four example models listed below are found in the 'models' folder

/papas/model/CADmodel ../models/run2.stl
/papas/model/translate 200 -125 0 mm
/papas/model/translatePMT 0 -74.5 0 mm

#/papas/model/CADmodel ../models/EMprototype.stl
#/papas/model/translate 0 0 0 mm
#/papas/model/translatePMT 0 -74.5 0 mm

#/papas/model/CADmodel ../models/EMprototypeSingle.stl
#/papas/model/translate 175.25 -27.75 -8 mm
#/papas/model/translatePMT 0 0 0 mm

#/papas/model/CADmodel ../models/2020WC.stl
#/papas/model/rotate 0 0 90
#/papas/model/translate 0 -319 0 mm
#/papas/model/translatePMT 0 -119 0 mm

#----- Set surface properties of the light guide -----
#/papas/surface/Model unified
#/papas/surface/Type dielectric_metal
#/papas/surface/Finish ground
#/papas/surface/SigmaAlpha .1
#/papas/surface/Property SPECULARLOBECONSTANT 0.000002 .4 0.000008 .4
#/papas/surface/Property SPECULARSPIKECONSTANT 0.000002 .1 0.000008 .1
#/papas/surface/Property BACKSCATTERCONSTANT 0.000002 .05 0.000008 .05
#/papas/surface/Property REFLECTIVITY 0.000002 .89 0.000008 .89


#----- Set the refractive index of the gas the light guide is inside of -----
#/papas/gasProperty RINDEX 0.000002 1.0 0.000008 1.0
